added Inventory Resource, Mining update and Shop Sell
TheUndo/gogobot pull request #22
Opened 2024-05-14 20:17 UTC by ItsMeAdil

2024-05-17 11:28 UTC, TheUndo requested changes
The logic looks ok but what I'm wondering is, is the sell and inventory only for "resources"? When we have non-resource items, is your intention to use the same system as for resources or create a parallel system? My concern is the shop/inventory/sell is closely tied to mine when that is only one aspect of the shop system

2024-05-17 11:28 UTC, TheUndo commented on bot/interactions/commands/economy/economyMine.ts
> +    if (resourceData.id !== "" && resourceData.id !== "") {
?
```suggestion
    if (resourceData.id) {
```

2024-05-17 11:28 UTC, TheUndo commented on bot/interactions/commands/economy/shop/economyFunction.ts
> +type dataType = {
```suggestion
type DataType = {
```

2024-05-17 11:28 UTC, TheUndo commented on bot/interactions/commands/economy/shop/economyFunction.ts
> +type dataType = {
maybe rename to something less generic?

2024-05-17 11:28 UTC, TheUndo commented on bot/interactions/commands/economy/shop/economyFunction.ts
> +  console.log(userClan?.level);
```suggestion
```

2024-05-17 11:28 UTC, TheUndo commented on bot/interactions/commands/economy/shop/economyFunction.ts
> +};
all of these types should be pascal case

2024-05-17 11:28 UTC, TheUndo commented on bot/interactions/commands/economy/shop/economyShop.ts
> +type fieldValue = {
```suggestion
type FieldValue = {
```

2024-05-17 11:28 UTC, TheUndo commented on bot/interactions/commands/inventory/inventoryInteraction.ts
> +      content: "This interaction is an button",
```suggestion
      content: "This interaction is a button",
```

2024-05-18 10:01 UTC, ItsMeAdil commented
Im planning on doing like what i did to inventory where we create a whole new embed page for different items other than resources.

Example:
- for resource
```ts
export async function economyShopResourceSellMenu(
  interactionContext: InteractionContext,
  interaction: AnyInteraction,
) {}
```

- pet
```ts
export async function economyShopPetSellMenu(
  interactionContext: InteractionContext,
  interaction: AnyInteraction,
) {}
```

2024-05-18 14:13 UTC, TheUndo approved these changes

2024-05-18 14:13 UTC, merged